### ISSUE TITLE
Error when changing email

### ISSUE THREAD

**Issue by CorpusCallosum** [CirclesUBI/circles-prototype#10]
Attempt to change email address in profile settings page, results in the following error:

Runtime Error
Uncaught (in promise): TypeError: Cannot read property 'on' of undefined TypeError: Cannot read property 'on' of undefined at Promise (http://localhost:8100/build/main.js:584:27) at new t (http://localhost:8100/build/polyfills.js:3:15044) at StorageService.<anonymous> (http://localhost:8100/build/main.js:583:20) at Generator.next (<anonymous>) at http://localhost:8100/build/main.js:512:71 at new t (http://localhost:8100/build/polyfills.js:3:15044) at webpackJsonp.189.__awaiter (http://localhost:8100/build/main.js:508:12) at StorageService.uploadFile (http://localhost:8100/build/main.js:573:16) at Promise (http://localhost:8100/build/main.js:317:37) at new t (http://localhost:8100/build/polyfills.js:3:15044)
Stack
Error: Uncaught (in promise): TypeError: Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at Promise (http://localhost:8100/build/main.js:584:27)
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at StorageService.<anonymous> (http://localhost:8100/build/main.js:583:20)
    at Generator.next (<anonymous>)
    at http://localhost:8100/build/main.js:512:71
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at webpackJsonp.189.__awaiter (http://localhost:8100/build/main.js:508:12)
    at StorageService.uploadFile (http://localhost:8100/build/main.js:573:16)
    at Promise (http://localhost:8100/build/main.js:317:37)
    at new t (http://localhost:8100/build/polyfills.js:3:15044)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at c (http://localhost:8100/build/polyfills.js:3:13221)
    at http://localhost:8100/build/polyfills.js:3:14067
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4501:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at HTMLFormElement.invoke (http://localhost:8100/build/polyfills.js:3:10985)
Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.4
Angular Core: 4.3.4
Angular Compiler CLI: 4.3.4
Node: 6.10.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

![screen shot 2017-08-30 at 9 03 44 pm](https://user-images.githubusercontent.com/609852/29901583-d20ce364-8dc6-11e7-8788-7478ed1a4254.png)

**Comment by edzillion** [comment]
fixed in 6ac1d8337209bee195ac9a26d41dfdf0e99705c6

cheers
