### ISSUE TITLE
Error when creating a new account

### ISSUE THREAD

**Issue by CorpusCallosum** [CirclesUBI/circles-prototype#13]
Getting the following error when I try to create a new account (master branch):
Runtime Error
_co.onSlideDidChange is not a function
Stack
TypeError: _co.onSlideDidChange is not a function
    at Object.eval [as handleEvent] (ng:///AppModule/WelcomePage.ngfactory.js:542:31)
    at handleEvent (http://localhost:8100/build/vendor.js:12617:138)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:14078:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:13666:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9221:21)
    at http://localhost:8100/build/vendor.js:11383:20
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/vendor.js:4267:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:16425:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:16372:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:16312:26)

Ionic Framework: 3.6.0
Ionic App Scripts: 2.1.4
Angular Core: 4.3.4
Angular Compiler CLI: 4.3.4
Node: 6.10.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

![screen shot 2017-09-06 at 7 31 45 pm](https://user-images.githubusercontent.com/609852/30139218-845b1a54-933a-11e7-813f-847710ca1e4a.png)

**Comment by edzillion** [comment]
This one was a merge bug, it's already fixed.
